<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net8.0</TargetFramework>
        <LangVersion>12.0</LangVersion>
        <Nullable>enable</Nullable>
        <AssemblyName>Newfarm.Host</AssemblyName>
        <RootNamespace>Newfarm.Host</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\Newfarm.Server\Newfarm.Server.csproj" />
    </ItemGroup>

</Project>
